// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwycllbxmjdlcmjbkbbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3eWNsbGJ4bWpkbGNtamJrYmJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyODY2NDgsImV4cCI6MjA2OTg2MjY0OH0.amZjHRfaHVAaXH-4_SG-AHX2CZ0wAelRHDS7Q9mjzBw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});